/* callafunction.c generated by valac 0.34.4, the Vala compiler
 * generated from callafunction.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <lua.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <lauxlib.h>

#define _lua_close0(var) ((var == NULL) ? NULL : (var = (lua_close (var), NULL)))



gint my_func (lua_State* vm);
gint _vala_main (gchar** args, int args_length1);
static gint _my_func_lua_cfunction (lua_State* vm);


gint my_func (lua_State* vm) {
	gint result = 0;
	FILE* _tmp0_ = NULL;
	lua_State* _tmp1_ = NULL;
	gdouble _tmp2_ = 0.0;
	g_return_val_if_fail (vm != NULL, 0);
	_tmp0_ = stdout;
	_tmp1_ = vm;
	_tmp2_ = lua_tonumber (_tmp1_, 1);
	fprintf (_tmp0_, "Vala Code From Lua Code! (%f)\n", _tmp2_);
	result = 1;
	return result;
}


static gint _my_func_lua_cfunction (lua_State* vm) {
	gint result;
	result = my_func (vm);
	return result;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	lua_State* vm = NULL;
	lua_State* _tmp0_ = NULL;
	_tmp0_ = (lua_State*) luaL_newstate ();
	vm = _tmp0_;
	luaL_openlibs (vm);
	lua_register (vm, "my_func", _my_func_lua_cfunction);
	luaL_dofile (vm, "code.lua");
	luaL_dostring (vm, "test_code()");
	result = 0;
	_lua_close0 (vm);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return _vala_main (argv, argc);
}



