/* inclass-static.c generated by valac 0.34.4, the Vala compiler
 * generated from inclass-static.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <lua.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <lauxlib.h>
#include <gobject/gvaluecollector.h>


#define LUA_TEST_TYPE_LUA_TEST (lua_test_lua_test_get_type ())
#define LUA_TEST_LUA_TEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUA_TEST_TYPE_LUA_TEST, LuaTestLuaTest))
#define LUA_TEST_LUA_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LUA_TEST_TYPE_LUA_TEST, LuaTestLuaTestClass))
#define LUA_TEST_IS_LUA_TEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUA_TEST_TYPE_LUA_TEST))
#define LUA_TEST_IS_LUA_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LUA_TEST_TYPE_LUA_TEST))
#define LUA_TEST_LUA_TEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LUA_TEST_TYPE_LUA_TEST, LuaTestLuaTestClass))

typedef struct _LuaTestLuaTest LuaTestLuaTest;
typedef struct _LuaTestLuaTestClass LuaTestLuaTestClass;
typedef struct _LuaTestLuaTestPrivate LuaTestLuaTestPrivate;
#define _lua_close0(var) ((var == NULL) ? NULL : (var = (lua_close (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _LuaTestParamSpecLuaTest LuaTestParamSpecLuaTest;

struct _LuaTestLuaTest {
	GTypeInstance parent_instance;
	volatile int ref_count;
	LuaTestLuaTestPrivate * priv;
};

struct _LuaTestLuaTestClass {
	GTypeClass parent_class;
	void (*finalize) (LuaTestLuaTest *self);
};

struct _LuaTestParamSpecLuaTest {
	GParamSpec parent_instance;
};


static gpointer lua_test_lua_test_parent_class = NULL;

gpointer lua_test_lua_test_ref (gpointer instance);
void lua_test_lua_test_unref (gpointer instance);
GParamSpec* lua_test_param_spec_lua_test (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void lua_test_value_set_lua_test (GValue* value, gpointer v_object);
void lua_test_value_take_lua_test (GValue* value, gpointer v_object);
gpointer lua_test_value_get_lua_test (const GValue* value);
GType lua_test_lua_test_get_type (void) G_GNUC_CONST;
enum  {
	LUA_TEST_LUA_TEST_DUMMY_PROPERTY
};
static gint lua_test_lua_test_my_func (lua_State* vm);
static gint lua_test_lua_test_main (gchar** args, int args_length1);
static gint _lua_test_lua_test_my_func_lua_cfunction (lua_State* vm);
LuaTestLuaTest* lua_test_lua_test_new (void);
LuaTestLuaTest* lua_test_lua_test_construct (GType object_type);
static void lua_test_lua_test_finalize (LuaTestLuaTest* obj);


static gint lua_test_lua_test_my_func (lua_State* vm) {
	gint result = 0;
	FILE* _tmp0_ = NULL;
	lua_State* _tmp1_ = NULL;
	gdouble _tmp2_ = 0.0;
	g_return_val_if_fail (vm != NULL, 0);
	_tmp0_ = stdout;
	_tmp1_ = vm;
	_tmp2_ = lua_tonumber (_tmp1_, 1);
	fprintf (_tmp0_, "Vala Code From Lua Code! (%f)\n", _tmp2_);
	result = 1;
	return result;
}


static gint _lua_test_lua_test_my_func_lua_cfunction (lua_State* vm) {
	gint result;
	result = lua_test_lua_test_my_func (vm);
	return result;
}


static gint lua_test_lua_test_main (gchar** args, int args_length1) {
	gint result = 0;
	gchar* code = NULL;
	gchar* _tmp0_ = NULL;
	lua_State* vm = NULL;
	lua_State* _tmp1_ = NULL;
	_tmp0_ = g_strdup ("\n" \
"                            print \"Lua Code From Vala Code!\"\n" \
"                            my_func(33)\n" \
"                        ");
	code = _tmp0_;
	_tmp1_ = (lua_State*) luaL_newstate ();
	vm = _tmp1_;
	luaL_openlibs (vm);
	lua_register (vm, "my_func", _lua_test_lua_test_my_func_lua_cfunction);
	luaL_dostring (vm, code);
	result = 0;
	_lua_close0 (vm);
	_g_free0 (code);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return lua_test_lua_test_main (argv, argc);
}


LuaTestLuaTest* lua_test_lua_test_construct (GType object_type) {
	LuaTestLuaTest* self = NULL;
	self = (LuaTestLuaTest*) g_type_create_instance (object_type);
	return self;
}


LuaTestLuaTest* lua_test_lua_test_new (void) {
	return lua_test_lua_test_construct (LUA_TEST_TYPE_LUA_TEST);
}


static void lua_test_value_lua_test_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void lua_test_value_lua_test_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		lua_test_lua_test_unref (value->data[0].v_pointer);
	}
}


static void lua_test_value_lua_test_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = lua_test_lua_test_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer lua_test_value_lua_test_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* lua_test_value_lua_test_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		LuaTestLuaTest* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = lua_test_lua_test_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* lua_test_value_lua_test_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	LuaTestLuaTest** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = lua_test_lua_test_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* lua_test_param_spec_lua_test (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	LuaTestParamSpecLuaTest* spec;
	g_return_val_if_fail (g_type_is_a (object_type, LUA_TEST_TYPE_LUA_TEST), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer lua_test_value_get_lua_test (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, LUA_TEST_TYPE_LUA_TEST), NULL);
	return value->data[0].v_pointer;
}


void lua_test_value_set_lua_test (GValue* value, gpointer v_object) {
	LuaTestLuaTest* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, LUA_TEST_TYPE_LUA_TEST));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, LUA_TEST_TYPE_LUA_TEST));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		lua_test_lua_test_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		lua_test_lua_test_unref (old);
	}
}


void lua_test_value_take_lua_test (GValue* value, gpointer v_object) {
	LuaTestLuaTest* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, LUA_TEST_TYPE_LUA_TEST));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, LUA_TEST_TYPE_LUA_TEST));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		lua_test_lua_test_unref (old);
	}
}


static void lua_test_lua_test_class_init (LuaTestLuaTestClass * klass) {
	lua_test_lua_test_parent_class = g_type_class_peek_parent (klass);
	((LuaTestLuaTestClass *) klass)->finalize = lua_test_lua_test_finalize;
}


static void lua_test_lua_test_instance_init (LuaTestLuaTest * self) {
	self->ref_count = 1;
}


static void lua_test_lua_test_finalize (LuaTestLuaTest* obj) {
	LuaTestLuaTest * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LUA_TEST_TYPE_LUA_TEST, LuaTestLuaTest);
	g_signal_handlers_destroy (self);
}


GType lua_test_lua_test_get_type (void) {
	static volatile gsize lua_test_lua_test_type_id__volatile = 0;
	if (g_once_init_enter (&lua_test_lua_test_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { lua_test_value_lua_test_init, lua_test_value_lua_test_free_value, lua_test_value_lua_test_copy_value, lua_test_value_lua_test_peek_pointer, "p", lua_test_value_lua_test_collect_value, "p", lua_test_value_lua_test_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (LuaTestLuaTestClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lua_test_lua_test_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LuaTestLuaTest), 0, (GInstanceInitFunc) lua_test_lua_test_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType lua_test_lua_test_type_id;
		lua_test_lua_test_type_id = g_type_register_fundamental (g_type_fundamental_next (), "LuaTestLuaTest", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&lua_test_lua_test_type_id__volatile, lua_test_lua_test_type_id);
	}
	return lua_test_lua_test_type_id__volatile;
}


gpointer lua_test_lua_test_ref (gpointer instance) {
	LuaTestLuaTest* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void lua_test_lua_test_unref (gpointer instance) {
	LuaTestLuaTest* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		LUA_TEST_LUA_TEST_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



