/* inclass.c generated by valac 0.34.4, the Vala compiler
 * generated from inclass.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <lua.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <lauxlib.h>

#define _lua_close0(var) ((var == NULL) ? NULL : (var = (lua_close (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))



gint lua_test_my_func (lua_State* vm);
gint lua_test_main (gchar** args, int args_length1);
static gint _lua_test_my_func_lua_cfunction (lua_State* vm);


gint lua_test_my_func (lua_State* vm) {
	gint result = 0;
	FILE* _tmp0_ = NULL;
	lua_State* _tmp1_ = NULL;
	gdouble _tmp2_ = 0.0;
	g_return_val_if_fail (vm != NULL, 0);
	_tmp0_ = stdout;
	_tmp1_ = vm;
	_tmp2_ = lua_tonumber (_tmp1_, 1);
	fprintf (_tmp0_, "Vala Code From Lua Code! (%f)\n", _tmp2_);
	result = 1;
	return result;
}


static gint _lua_test_my_func_lua_cfunction (lua_State* vm) {
	gint result;
	result = lua_test_my_func (vm);
	return result;
}


gint lua_test_main (gchar** args, int args_length1) {
	gint result = 0;
	gchar* code = NULL;
	gchar* _tmp0_ = NULL;
	lua_State* vm = NULL;
	lua_State* _tmp1_ = NULL;
	_tmp0_ = g_strdup ("\n" \
"                    print \"Lua Code From Vala Code!\"\n" \
"                    my_func(33)\n" \
"                ");
	code = _tmp0_;
	_tmp1_ = (lua_State*) luaL_newstate ();
	vm = _tmp1_;
	luaL_openlibs (vm);
	lua_register (vm, "my_func", _lua_test_my_func_lua_cfunction);
	luaL_dostring (vm, code);
	result = 0;
	_lua_close0 (vm);
	_g_free0 (code);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return lua_test_main (argv, argc);
}



